#25 Unit tests
fungover/system2024 pull request #67
Opened 2024-12-13 13:02 UTC by MikaelaMathisson

**Unit Tests for User, Role, and Permission Entities**
Closes #25 

**Description:**
This pull request adds a comprehensive set of unit tests for the `User`, `Role`, and `Permission` entities. 
The following scenarios are tested:

**User Tests:**
- Validation of maximum length constraints for `name`, `email`, and `password`

**Role Tests:**
- Validation for non-null `name`
- Validation of maximum length constraints for `name`
- Initial state of role users and permissions
- Adding a user to a role

**Permission Tests:**
- Validation for non-null `name` and `description`
- Validation of maximum length constraints for `name` and `description`
- Initial state of permission roles
- Adding a role to a permission

**Test Coverage:**
- `UserTest`
  - `userNameShouldBeWithinMaxLength`
  - `userEmailShouldBeWithinMaxLength`
  - `userPasswordShouldBeWithinMaxLength`
- `RoleTest`
  - `roleNameShouldNotBeNull`
  - `roleNameShouldHaveMaxLength`
  - `roleUsersShouldBeEmptyInitially`
  - `rolePermissionsShouldBeEmptyInitially`
  - `addUserToRole`
- `PermissionTest`
  - `permissionNameShouldNotBeNull`
  - `permissionDescriptionShouldNotBeNull`
  - `permissionNameShouldHaveMaxLength`
  - `permissionDescriptionShouldHaveMaxLength`
  - `permissionRolesShouldBeEmptyInitially`
  - `addRoleToPermission`

---

2024-12-16 09:17 UTC, JrSchoolAccount commented
Found duplicate repository for user.
This needs to be changed and pushed 😃
<img width="373" alt="Screenshot 2024-12-16 at 10 12 47" src="https://github.com/user-attachments/assets/8c55f5ee-520b-41f5-a6e6-cf5b0f044772" />

2024-12-18 10:43 UTC, oskber approved these changes
Looks like well-structured tests. Good that you made some of the changes suggested by the AI 👍

2024-12-18 16:30 UTC, AlbinNils98 requested changes
I think the tests looks great! Well structured and easy to understand.

Though i believe we should implement the suggestions provided by Coderabbit, as they make strong points about ensuring comprehensive test coverage for the entities. Specifically, this includes validating all fields (e.g., lastname), testing thrown exceptions, and verifying both sides of the relationships.

2024-12-18 16:30 UTC, AlbinNils98 commented on src/test/java/org/fungover/system2024/entities/UserTest.java
> +}
Since my merged PR implementing sending list of users via GraphQL query i changed it so there is a first- and lastname in the db. I think it would be appropriate to implement a validation test for the lastname value also.

2024-12-18 17:28 UTC, MikaelaMathisson commented
@AlbinNils98 Changes are added :) I added the throw exception to Role.java but to be able to test exceptions on all of it, it needs to be added to all the files in entities and thats not on this issue. Did add the other things though 👍

2024-12-18 17:30 UTC, MikaelaMathisson commented on src/test/java/org/fungover/system2024/entities/UserTest.java
> +}
Added :)

2024-12-18 18:23 UTC, AlbinNils98 commented
> > @AlbinNils98 Changes are added :) I added the throw exception to Role.java but to be able to test exceptions on all of it, it needs to be added to all the files in entities and thats not on this issue. Did add the other things though 👍
> 
> Thats great! We can absolutely add specific Illegal argument exceptions to the setters in the enities but there is already a constraintViolation exception in place through jakarta.validation with the validation annotations in the entities. Coderabbit confused me in saying that the validation should throw IllegalArgumentException, but that it does not unless we add it.
> 
> Maybe i am misunderstanding what these tests should do but if we test the entities, shouldn't we test the actual validation of the fields? Now we only test that the setters and getters work, right?

2024-12-18 19:09 UTC, MikaelaMathisson commented
> > @AlbinNils98 Changes are added :) I added the throw exception to Role.java but to be able to test exceptions on all of it, it needs to be added to all the files in entities and thats not on this issue. Did add the other things though 👍
> 
> 
> 
> Thats great! 
> 
> We can absolutely add specific Illegal argument exceptions to the setters in the enities but there is already a  constraintViolation exception in place through jakarta.validation with the validation annotations in the entities.
> 
> Coderabbit confused me in saying that the setters should throw IllegalArgumentException, but that it does not unless we add it.
> 
> 
> 
> Maybe i am misunderstanding what these tests should do but if we test the entities, shouldn't we test the actual validation of the fields? Now we only test that the setters and getter methods work, right?
> 
> 
> 
> I believe this could be achieved with the use of a validator through validatorFactory in the test.
> 
> 
> 
> 

Will look into this tomorrow!

2024-12-18 21:57 UTC, MatsJoh50 requested changes
While the tests are good and testing the outer limits and the Set Functions of each role and user, we are not testing outside the limits.

Code example to follow works for the user settings.
```
  @Test
    void userPasswordNotOverMaxLength() {
        // Create a Validator
        ValidatorFactory factory = Validation.buildDefaultValidatorFactory();
        Validator validator = factory.getValidator();

        // Create a User object and set an invalid last_name
        User user = new User();
        user.setPassword("A".repeat(61));

        // Validate the User object
        Set<ConstraintViolation<User>> violations = validator.validate(user);

        // Assert that there is a validation error
        assertFalse(violations.isEmpty());
        assertTrue(violations.stream()
                .anyMatch(violation -> violation.getPropertyPath().toString().equals("password")
                        && violation.getMessage().contains("size must be between")));
    }
```

2024-12-19 10:52 UTC, AlbinNils98 submitted a review, later dismissed
Nice work with the changes! 

I think that the test coverage is good now.

I saw that coderabbit had some nitpick comments if you want to look into those, but again i think we have covered enough with the tests as they are.

Approving!

2024-12-19 10:53 UTC, MikaelaMathisson commented on src/main/java/org/fungover/system2024/user/entity/User.java
> +    @NotBlank
Yes! It eliminates potential empty strings, null values and white spaces 👍

2024-12-19 12:38 UTC, MatsJoh50 approved these changes
Great changes and good catches on more cases sush as null and blanks.

2024-12-19 13:30 UTC, MatsJoh50 approved these changes
Great job with the extentions of tetsts since last review.

2024-12-19 17:12 UTC, MatsJoh50 approved these changes
Great job getting all commits verified, everything  looks as before and thus working fine.

2024-12-19 17:25 UTC, ConnyPettersson approved these changes
Good job! All the tests are passing, and everything looks in order.

2024-12-19 17:25 UTC, merged