27 internationalization i18n
fungover/system2024 pull request #75
Opened 2024-12-16 22:59 UTC by HannaRosberg

**Description**
This pull request introduces internationalization (i18n) support to the frontend, allowing the application to be displayed in three languages:

- English (default)
- Swedish
- Spanish

**Key Changes**

1. **i18n Configuration**
- Added an i18n.ts file to set up the i18next library.
- Configured translations for the following keys:
  - welcome: Translates the welcome message.
  - changeLanguage: Button text to change the language.
  - visitCake: Link text to navigate to the /cake page.
  - cakeText: Text displayed on the /cake page along with the emoji.
 
2. **Frontend Integration**
- Updated the App.tsx component to display translatable text for welcome and changeLanguage.
- Updated /cake route to include localized text below the cake emoji.
- Used useTranslation hook to enable language switching functionality.

3. **Router Setup**
- Adjusted React Router in main.tsx to ensure compatibility with the i18n integration.

4. **UI for Language Switching**
- Added a menu for switching between English, Swedish, and Spanish.

**How to Test**
- Run the frontend locally:
  - npm install
  - npm run dev

**Verify that:**
The app defaults to English.
Language switching works as expected.
All translated text (including /cake page) changes dynamically.

### **Why we need the multilingual features**
This PR is part of the multilingual feature initiative to support users in different regions, aligning with the project's goal to improve accessibility and user experience.

**I will add this feature to more pages in the frontend when needed.**

2024-12-17 11:15 UTC, ConnyPettersson submitted a review, later dismissed
Overall, the code appears clean and easy to follow, especially in App.tsx where the language buttons and text strings are clearly separated. If additional translatable content or languages are introduced, it could be beneficial to extract the language-switching logic and a possible button generator into a separate component for better separation of logic and presentation. Adding tests to ensure long-term quality would also be worth considering.

2024-12-18 13:52 UTC, MikaelaMathisson requested changes
This PR solves the issue for Internationalization well.

I think the code is simple. very readable and has great variable names. Its easy to follow.

I did notice though, that the coderabbit suggested the following:
 "Add error handling and loading state for translations"
I think this is necessary for this type of issue and would recommend looking through the changes that the coderabbit suggested, to make the code handle error or loading states.

2024-12-19 13:22 UTC, MatsJoh50 submitted a review, later dismissed
Great start for i18n and using /cake as a small tutorial/sample is  great!

I like the suggestion from coderabbit to  refactor each page to a seperate translation file for ease of scaling.

2024-12-19 13:22 UTC, MatsJoh50 commented on frontend/src/i18n.ts
> +    },
As one who never worked with i18n I feel that this is a great way to keep each page clean and easy to work with, especilly when the app grows with more propper content.

2024-12-23 08:02 UTC, MikaelaMathisson approved these changes
I think this looks great after the changes. Good job on adding error and loading states 👍

2024-12-23 08:06 UTC, oskber approved these changes
Nice work with the translation implementation 👍

2024-12-23 08:55 UTC, merged